package nro.skill;

import java.util.ArrayList;

public class NoiTaiTemplate {
    public static ArrayList<NoiTai> listNoiTaiTD = new ArrayList<NoiTai>();
    public static ArrayList<NoiTai> listNoiTaiNM = new ArrayList<NoiTai>();
    public static ArrayList<NoiTai> listNoiTaiXD = new ArrayList<NoiTai>();

    public static void initNoiTai() {
        NoiTai _noiTai = null;
        //NOI TAI TRAI DAT
        _noiTai = new NoiTai((byte)0, (short)0);
        _noiTai.idIcon = (short)5223;
        _noiTai.infoTemp = "Chưa có nội tại";
        _noiTai.infoHead = "Chưa có nội tại";
        _noiTai.infoFoot = "Chưa có nội tại";
        NoiTaiTemplate.listNoiTaiTD.add(_noiTai);
        _noiTai = new NoiTai((byte)1, (short)0);
        _noiTai.idIcon = (short)539;
        _noiTai.min = 5;
        _noiTai.max = 25;
        _noiTai.idSkill = (byte)0;
        _noiTai.infoTemp = "Chiêu đấm Dragon +5% đến 25% sát thương";
        _noiTai.infoHead = "Chiêu đấm Dragon +";
        _noiTai.infoFoot = "% sát thương[5 đến 25]";
        NoiTaiTemplate.listNoiTaiTD.add(_noiTai);
        _noiTai = new NoiTai((byte)2, (short)0);
        _noiTai.idIcon = (short)569;
        _noiTai.min = 5;
        _noiTai.max = 25;
        _noiTai.idSkill = (byte)1;
        _noiTai.infoTemp = "Chiêu Kamejoko +5% đến 25% sát thương";
        _noiTai.infoHead = "Chiêu Kamejoko +";
        _noiTai.infoFoot = "% sát thương[5 đến 25]";
        NoiTaiTemplate.listNoiTaiTD.add(_noiTai);
        _noiTai = new NoiTai((byte)3, (short)0);
        _noiTai.idIcon = (short)5222;
        _noiTai.min = 10;
        _noiTai.max = 35;
        _noiTai.idSkill = (byte)6;
        _noiTai.infoTemp = "Thái dương hạ san +10% đến 35% tốc độ hồi phục";
        _noiTai.infoHead = "Thái dương hạ san +";
        _noiTai.infoFoot = "% tốc độ hồi phục[10 đến 35]";
        NoiTaiTemplate.listNoiTaiTD.add(_noiTai);
        _noiTai = new NoiTai((byte)4, (short)0);
        _noiTai.idIcon = (short)5222;
        _noiTai.min = 15;
        _noiTai.max = 55;
        _noiTai.idSkill = (byte)10;
        _noiTai.infoTemp = "Quả cầu kênh khi +15% đến 55% tốc độ hồi phục";
        _noiTai.infoHead = "Quả cầu kênh khi +";
        _noiTai.infoFoot = "% tốc độ hồi phục[15 đến 55]";
        NoiTaiTemplate.listNoiTaiTD.add(_noiTai);
        _noiTai = new NoiTai((byte)5, (short)0);
        _noiTai.idIcon = (short)568;
        _noiTai.min = 50;
        _noiTai.max = 150;
        _noiTai.idSkill = (byte)20;
        _noiTai.infoTemp = "Dịch chuyển tức thời +50% đến 150% sát thương đòn kế";
        _noiTai.infoHead = "Dịch chuyển tức thời +";
        _noiTai.infoFoot = "% sát thương đòn kế[50 đến 150]";
        NoiTaiTemplate.listNoiTaiTD.add(_noiTai);
        _noiTai = new NoiTai((byte)6, (short)0);
        _noiTai.idIcon = (short)568;
        _noiTai.min = 50;
        _noiTai.max = 150;
        _noiTai.idSkill = (byte)22;
        _noiTai.infoTemp = "Thôi miên +50% đến 150% sát thương đòn kế";
        _noiTai.infoHead = "Thôi miên +";
        _noiTai.infoFoot = "% sát thương đòn kế[50 đến 150]";
        NoiTaiTemplate.listNoiTaiTD.add(_noiTai);
        _noiTai = new NoiTai((byte)7, (short)0);
        _noiTai.idIcon = (short)5222;
        _noiTai.min = 15;
        _noiTai.max = 55;
        _noiTai.idSkill = (byte)19;
        _noiTai.infoTemp = "Khiên năng lượng +15% đến 55% tốc độ hồi phục";
        _noiTai.infoHead = "Khiên năng lượng +";
        _noiTai.infoFoot = "% tốc độ hồi phục[15 đến 55]";
        NoiTaiTemplate.listNoiTaiTD.add(_noiTai);
        _noiTai = new NoiTai((byte)8, (short)0);
        _noiTai.idIcon = (short)930;
        _noiTai.min = 25;
        _noiTai.max = 300;
        _noiTai.idSkill = (byte)(-2);
        _noiTai.infoTemp = "Vàng rơi từ quái +25% đến 300%";
        _noiTai.infoHead = "Vàng rơi từ quái +";
        _noiTai.infoFoot = "%[25 đến 300]";
        NoiTaiTemplate.listNoiTaiTD.add(_noiTai);
        _noiTai = new NoiTai((byte)9, (short)0);
        _noiTai.idIcon = (short)3783;
        _noiTai.min = 5;
        _noiTai.max = 35;
        _noiTai.idSkill = (byte)(-3);
        _noiTai.infoTemp = "Sức mạnh và tiềm năng khi đánh quái +5% đến 35%";
        _noiTai.infoHead = "Sức mạnh và tiềm năng khi đánh quái +";
        _noiTai.infoFoot = "%[5 đến 35]";
        NoiTaiTemplate.listNoiTaiTD.add(_noiTai);
        _noiTai = new NoiTai((byte)10, (short)0);
        _noiTai.idIcon = (short)716;
        _noiTai.min = 20;
        _noiTai.max = 50;
        _noiTai.idSkill = (byte)(-4);
        _noiTai.infoTemp = "Chí mạng liên tục khi HP dưới 20% đến 50%";
        _noiTai.infoHead = "Chí mạng liên tục khi HP dưới ";
        _noiTai.infoFoot = "%[20 đến 50]";
        NoiTaiTemplate.listNoiTaiTD.add(_noiTai);

        //NOI TAI NAMEK
        _noiTai = new NoiTai((byte)0, (short)0);
        _noiTai.idIcon = (short)5223;
        _noiTai.infoTemp = "Chưa có nội tại";
        _noiTai.infoHead = "Chưa có nội tại";
        _noiTai.infoFoot = "Chưa có nội tại";
        NoiTaiTemplate.listNoiTaiNM.add(_noiTai);
        _noiTai = new NoiTai((byte)1, (short)0);
        _noiTai.idIcon = (short)569;
        _noiTai.min = 5;
        _noiTai.max = 25;
        _noiTai.idSkill = (byte)2;
        _noiTai.infoTemp = "Chiêu đấm Demo +5% đến 25% sát thương";
        _noiTai.infoHead = "Chiêu đấm Demo +";
        _noiTai.infoFoot = "% sát thương[2 đến 25]";
        NoiTaiTemplate.listNoiTaiNM.add(_noiTai);
        _noiTai = new NoiTai((byte)2, (short)0);
        _noiTai.idIcon = (short)569;
        _noiTai.min = 5;
        _noiTai.max = 25;
        _noiTai.idSkill = (byte)3;
        _noiTai.infoTemp = "Chiêu chưởng Masenko +5% đến 25% sát thương";
        _noiTai.infoHead = "Chiêu chưởng Masenko +";
        _noiTai.infoFoot = "% sát thương[2 đến 25]";
        NoiTaiTemplate.listNoiTaiNM.add(_noiTai);
        _noiTai = new NoiTai((byte)3, (short)0);
        _noiTai.idIcon = (short)5222;
        _noiTai.min = 15;
        _noiTai.max = 55;
        _noiTai.idSkill = (byte)7;
        _noiTai.infoTemp = "Trị thương +15% đến 55% tốc độ hồi phục";
        _noiTai.infoHead = "Trị thương +";
        _noiTai.infoFoot = "% tốc độ hồi phục[15 đến 55]";
        NoiTaiTemplate.listNoiTaiNM.add(_noiTai);
        _noiTai = new NoiTai((byte)4, (short)0);
        _noiTai.idIcon = (short)5222;
        _noiTai.min = 15;
        _noiTai.max = 55;
        _noiTai.idSkill = (byte)11;
        _noiTai.infoTemp = "Makankosappo +15% đến 55% tốc độ hồi phục";
        _noiTai.infoHead = "Makankosappo +";
        _noiTai.infoFoot = "% tốc độ hồi phục[15 đến 55]";
        NoiTaiTemplate.listNoiTaiNM.add(_noiTai);
        _noiTai = new NoiTai((byte)5, (short)0);
        _noiTai.idIcon = (short)5222;
        _noiTai.min = 15;
        _noiTai.max = 65;
        _noiTai.idSkill = (byte)12;
        _noiTai.infoTemp = "Đẻ trứng +15% đến 65% tốc độ hồi phục";
        _noiTai.infoHead = "Đẻ trứng +";
        _noiTai.infoFoot = "% tốc độ hồi phục[15 đến 65]";
        NoiTaiTemplate.listNoiTaiNM.add(_noiTai);
        _noiTai = new NoiTai((byte)6, (short)0);
        _noiTai.idIcon = (short)569;
        _noiTai.min = 5;
        _noiTai.max = 25;
        _noiTai.idSkill = (byte)17;
        _noiTai.infoTemp = "Liên hoàn +5% đến 25% sát thương";
        _noiTai.infoHead = "Liên hoàn +";
        _noiTai.infoFoot = "% sát thương[5 đến 25]";
        NoiTaiTemplate.listNoiTaiNM.add(_noiTai);
        _noiTai = new NoiTai((byte)7, (short)0);
        _noiTai.idIcon = (short)568;
        _noiTai.min = 50;
        _noiTai.max = 150;
        _noiTai.idSkill = (byte)18;
        _noiTai.infoTemp = "Biến Sôcôla +50% đến 150% sát thương đòn kế";
        _noiTai.infoHead = "Biến Sôcôla +";
        _noiTai.infoFoot = "% sát thương đòn kế[50 đến 150]";
        NoiTaiTemplate.listNoiTaiNM.add(_noiTai);
        _noiTai = new NoiTai((byte)8, (short)0);
        _noiTai.idIcon = (short)5222;
        _noiTai.min = 15;
        _noiTai.max = 55;
        _noiTai.idSkill = (byte)19;
        _noiTai.infoTemp = "Khiên năng lượng +15% đến 55% tốc độ hồi phục";
        _noiTai.infoHead = "Khiên năng lượng +";
        _noiTai.infoFoot = "% tốc độ hồi phục[15 đến 55]";
        NoiTaiTemplate.listNoiTaiNM.add(_noiTai);
        _noiTai = new NoiTai((byte)9, (short)0);
        _noiTai.idIcon = (short)930;
        _noiTai.min = 25;
        _noiTai.max = 300;
        _noiTai.idSkill = (byte)(-2);
        _noiTai.infoTemp = "Vàng rơi từ quái +25% đến 300%";
        _noiTai.infoHead = "Vàng rơi từ quái +";
        _noiTai.infoFoot = "%[25 đến 300]";
        NoiTaiTemplate.listNoiTaiNM.add(_noiTai);
        _noiTai = new NoiTai((byte)10, (short)0);
        _noiTai.idIcon = (short)3783;
        _noiTai.min = 5;
        _noiTai.max = 35;
        _noiTai.idSkill = (byte)(-3);
        _noiTai.infoTemp = "Sức mạnh và tiềm năng khi đánh quái +5% đến 35%";
        _noiTai.infoHead = "Sức mạnh và tiềm năng khi đánh quái +";
        _noiTai.infoFoot = "%[5 đến 35]";
        NoiTaiTemplate.listNoiTaiNM.add(_noiTai);
        _noiTai = new NoiTai((byte)11, (short)0);
        _noiTai.idIcon = (short)716;
        _noiTai.min = 20;
        _noiTai.max = 50;
        _noiTai.idSkill = (byte)(-4);
        _noiTai.infoTemp = "Chí mạng liên tục khi HP dưới 20% đến 50%";
        _noiTai.infoHead = "Chí mạng liên tục khi HP dưới ";
        _noiTai.infoFoot = "%[20 đến 50]";
        NoiTaiTemplate.listNoiTaiNM.add(_noiTai);

        //NOI TAI XAYDA
        _noiTai = new NoiTai((byte)0, (short)0);
        _noiTai.idIcon = (short)5223;
        _noiTai.infoTemp = "Chưa có nội tại";
        _noiTai.infoHead = "Chưa có nội tại";
        _noiTai.infoFoot = "Chưa có nội tại";
        NoiTaiTemplate.listNoiTaiXD.add(_noiTai);
        _noiTai = new NoiTai((byte)1, (short)0);
        _noiTai.idIcon = (short)569;
        _noiTai.min = 5;
        _noiTai.max = 25;
        _noiTai.idSkill = (byte)4;
        _noiTai.infoTemp = "Chiêu đấm Galick +5% đến 25% sát thương";
        _noiTai.infoHead = "Chiêu đấm Galick +";
        _noiTai.infoFoot = "% sát thương[2 đến 25]";
        NoiTaiTemplate.listNoiTaiXD.add(_noiTai);
        _noiTai = new NoiTai((byte)2, (short)0);
        _noiTai.idIcon = (short)569;
        _noiTai.min = 5;
        _noiTai.max = 25;
        _noiTai.idSkill = (byte)5;
        _noiTai.infoTemp = "Chiêu Atomic +5% đến 25% sát thương";
        _noiTai.infoHead = "Chiêu Atomic +";
        _noiTai.infoFoot = "% sát thương[2 đến 25]";
        NoiTaiTemplate.listNoiTaiXD.add(_noiTai);
        _noiTai = new NoiTai((byte)3, (short)0);
        _noiTai.idIcon = (short)569;
        _noiTai.min = 5;
        _noiTai.max = 25;
        _noiTai.idSkill = (byte)13;
        _noiTai.infoTemp = "Biến hình +5% đến 25% sát thương";
        _noiTai.infoHead = "Biến hình +";
        _noiTai.infoFoot = "% sát thương[2 đến 25]";
        NoiTaiTemplate.listNoiTaiXD.add(_noiTai);
        _noiTai = new NoiTai((byte)4, (short)0);
        _noiTai.idIcon = (short)5222;
        _noiTai.min = 15;
        _noiTai.max = 65;
        _noiTai.idSkill = (byte)14;
        _noiTai.infoTemp = "Tự phát nổ +15% đến 65% tốc độ hồi phục";
        _noiTai.infoHead = "Tự phát nổ +";
        _noiTai.infoFoot = "% tốc độ hồi phục[15 đến 65]";
        NoiTaiTemplate.listNoiTaiXD.add(_noiTai);
        _noiTai = new NoiTai((byte)5, (short)0);
        _noiTai.idIcon = (short)5222;
        _noiTai.min = 15;
        _noiTai.max = 65;
        _noiTai.idSkill = (byte)21;
        _noiTai.infoTemp = "Huýt sáo +15% đến 65% tốc độ hồi phục";
        _noiTai.infoHead = "Huýt sáo +";
        _noiTai.infoFoot = "% tốc độ hồi phục[15 đến 65]";
        NoiTaiTemplate.listNoiTaiXD.add(_noiTai);
        _noiTai = new NoiTai((byte)6, (short)0);
        _noiTai.idIcon = (short)568;
        _noiTai.min = 50;
        _noiTai.max = 150;
        _noiTai.idSkill = (byte)23;
        _noiTai.infoTemp = "Trói +50% đến 150% sát thương đòn kế";
        _noiTai.infoHead = "Trói +";
        _noiTai.infoFoot = "% sát thương đòn kế[50 đến 150]";
        NoiTaiTemplate.listNoiTaiXD.add(_noiTai);
        _noiTai = new NoiTai((byte)7, (short)0);
        _noiTai.idIcon = (short)5222;
        _noiTai.min = 15;
        _noiTai.max = 55;
        _noiTai.idSkill = (byte)19;
        _noiTai.infoTemp = "Khiên năng lượng +15% đến 55% tốc độ hồi phục";
        _noiTai.infoHead = "Khiên năng lượng +";
        _noiTai.infoFoot = "% tốc độ hồi phục[15 đến 55]";
        NoiTaiTemplate.listNoiTaiXD.add(_noiTai);
        _noiTai = new NoiTai((byte)8, (short)0);
        _noiTai.idIcon = (short)930;
        _noiTai.min = 25;
        _noiTai.max = 300;
        _noiTai.idSkill = (byte)(-2);
        _noiTai.infoTemp = "Vàng rơi từ quái +25% đến 300%";
        _noiTai.infoHead = "Vàng rơi từ quái +";
        _noiTai.infoFoot = "%[25 đến 300]";
        NoiTaiTemplate.listNoiTaiXD.add(_noiTai);
        _noiTai = new NoiTai((byte)9, (short)0);
        _noiTai.idIcon = (short)3783;
        _noiTai.min = 5;
        _noiTai.max = 35;
        _noiTai.idSkill = (byte)(-3);
        _noiTai.infoTemp = "Sức mạnh và tiềm năng khi đánh quái +5% đến 35%";
        _noiTai.infoHead = "Sức mạnh và tiềm năng khi đánh quái +";
        _noiTai.infoFoot = "%[5 đến 35]";
        NoiTaiTemplate.listNoiTaiXD.add(_noiTai);
        _noiTai = new NoiTai((byte)10, (short)0);
        _noiTai.idIcon = (short)716;
        _noiTai.min = 20;
        _noiTai.max = 50;
        _noiTai.idSkill = (byte)(-4);
        _noiTai.infoTemp = "Chí mạng liên tục khi HP dưới 20% đến 50%";
        _noiTai.infoHead = "Chí mạng liên tục khi HP dưới ";
        _noiTai.infoFoot = "%[20 đến 50]";
        NoiTaiTemplate.listNoiTaiXD.add(_noiTai);
    }
}
